name: homework
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.0
  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.13.1
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5 
  flutter_svg: ^2.0.7


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  assets:
    - assets/questions.json
    - assets/icons/
    - assets/fonts/inter/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/inter/Inter-Regular.ttf
        - asset: assets/fonts/inter/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/inter/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/inter/Inter-Bold.ttf
          weight: 700

flutter_launcher_icons:
  image_path: "assets/appicon/icon.png"
  android: true
  ios: true
  